### PR TITLE
Feat/support persistent recursive watches

### PR DESCRIPTION
**Pull request by P4ndaFR**
As describe in #32, This PR aims to implement addWatch/removeWatches/removeAllWatches introduced in Zookeeper 3.6.

I could use your advice on what tests to implement. 
Thanks in advance for the review.

### CODE REVIEW

**Comment by P4ndaFR** [comment]
Small update:
I don't know if implementing the `removeWatches` function the way I did is really useful.
From what I can understand, this function is made to remove watches assigned to a specific local `Watcher`.
Since with this API, the user does not have access to the watcher, I don't know if there is a point implementing it.

**Comment by davidledwards** [comment]
I'll review the commits this weekend.

**Comment by davidledwards** [comment]
A couple thoughts after brushing up on ZooKeeper after so many years.

To carry on with my original design theme of terse method names, I will change `addWatch` and `removeWatches` to `observe` and `unobserve`, respectively.

Also, I would like to avoid introducing the `WatchMode` type by making the persistent/recursive selection implicit by virtue of the method signature — `def observe(path: String, recursive: Boolean = false)`.

The `removeAllWatches` should probably not be defined on `BaseZK` because, semantically, the watches are only applicable on the watchable instances of ZK. Additionally, I'm trying to determine if this function is even necessary on the watchable instance. Still trying to reason about this...

The `WatcherType` trait will be changed to `Observer` to be consistent with the method name.

Let me merge and refactor as specified above and see how that goes. Stay tuned.

**Comment by P4ndaFR** [comment]
Thank you for taking the time to review.

> Also, I would like to avoid introducing the WatchMode type by making the persistent/recursive selection implicit by virtue of the method signature — def observe(path: String, recursive: Boolean = false).

Makes sense to have a boolean flag for the WatchMode, since the default value is `Persistent` and the optional value is `PersistentRecursive`.

Thanks for merging, I'll follow what's to come !

**Pull request merged**
