### PR TITLE
make sbt cross build 2.13 and 3.1 / scala 3 compatibility

### PR DESCRIPTION
**Pull request by ajrnz**
Here are some changes to make the project cross build to scala 3

    sbt ++2.13.10 test

and

    sbt ++3.1.3 test

pass the tests

### CODE REVIEW

**Comment by davidledwards** [comment]
Thanks for the PR. I'll get these changes merged and publish both versions.

**Comment by ajrnz** [comment]
Thanks. Much appreciated

**Comment by davidledwards** [comment]
New release with Scala 3 support.

https://github.com/davidledwards/zookeeper/tree/release-1.6.1

**Comment by ajrnz** [comment]
Thanks!

**Pull request merged**
